### PR TITLE
Add account holder to bank transfer information

### PR DESCRIPTION
**Pull request by eht16**
Follow-up of #19 with @b4n's feedback incoporated (as #19 was merged too fast).

### CODE REVIEW

**Comment by codebrainz** [comment]
Is this something people know how to do, generally? I only ask because I wouldn't have the slightest clue how to do this, but it could very well just be me. If not, maybe we should link to some instructions or something?

**Comment by frlan** [comment]
Doing a bank transfer should be basic knowledge at most people around Europe -- the bank account only accepts payments from SEPA anyway.

**Comment by codebrainz** [comment]
I see. It might be helpful to mention for the other 90% of the world's population that lives outside of the Single Euro Payment Area that's it's a Euro-only thing.

**Comment by frlan** [comment]
Personally I don't think it's needed.

**Comment by frlan** [comment]
While rethinking we should at least point out it's SEPA.

**Comment by eht16** [comment]
I guess we could also provide the SWIFT information so non-EU/SEPA
transfers would be possible.
However, then fees might be higher than the donation amount and so it's
useless.

Probably with #21 we are fine so far.

**Pull request merged**
