### PR TITLE
Geany e. V. General Assembly 2020 was done

### PR DESCRIPTION
**Pull request by frlan**

### CODE REVIEW

**Comment by eht16** [comment]
Previously we used "None planned" (see https://github.com/geany/www.geany.org/commit/d82f9412bae876a3764d0259a73d8b13e35141db).

@elextr what would you prefer?

**Comment by elextr** [comment]
Well, as the subject line is not part of a specific meeting report it does not relate to a specific date, so no need to use terms like "so far" or the formal "at this time" that relate to a point in time.  

I would just say "None scheduled".  

Then you can have "unscheduled" meetings at any time they are required by association law or by personal preference.

[Disclaimer: IANAL especially of German associations] :grin:

**Comment by frlan** [comment]
@elextr  The only set thing is, "one meeting per year" No date. It can be either at Jan, 1st or December, 31th --Only having a combined one at new years eve will not work unless you are sending out to invitations :D

**Comment by eht16** [comment]
I like ""None scheduled".
@frlan would you mind updating it?

**Pull request merged**
