### PR TITLE
Prepare for using more HTTPS

### PR DESCRIPTION
**Pull request by genodeftest**
1. upgrade some links to HTTPS
2. use protocol-relative URLs where possible, let the browser decide whether to use HTTP or HTTPS.

### CODE REVIEW

**Comment by b4n** [comment]
Why not use protocol-relative userls for Twitter and Facebook too?

Tho, FWIW changes LGTM (but some commits should probably be squashed together).

**Comment by genodeftest** [comment]
I think twitter and facebook use HTTPS only so there would be no gain in using a protocol-relative URL. Their servers will redirect to HTTPS URLs anyway.

And I didn't understand the other sentence. Maybe because English is not my first language and maybe because of abbrevitations.

**Comment by b4n** [comment]
BTW, note that this site isn't in production for real yet (although it probably should be finished and set up, but well)

**Comment by genodeftest** [comment]
Oh, and the only reason I can think of to still use HTTP on exaile.org is not having a certificate. Both facebook and twitter do have certificates for their domains.

**Comment by b4n** [comment]
> And I didn't understand the other sentence. Maybe because English is not my first language and maybe because of abbrevitations.

Sorry.  It reads:

Thoough, for what is worth (as I'm not very versed in the website) changes looks good to me (but some commits should probably be squashed together (merged to make only 1 commit out of a few)).

> Oh, and the only reason I can think of to still use HTTP on exaile.org is not having a certificate.

Our own isn't valid either I think.  And I just want to our current website and it seems quite broken with HTTPS… that's odd though.

**Comment by eht16** [comment]
As @b4n said, squashing the commits together would be nice.

About this not yet ready website:
I have some more changes pending to port the current code to Bootstrap3 and update everything to a newer Mezzanine version (the CMS used here). However, I'm currently waiting for the next Mezzanine release which should support Django 1.8.
And then, I want to finally work on this projet to get it finally running. Finally. :)

About SSL: currently we have a cacert.org SSL certificate for *.geany.org. This is not accepted by major browsers by default, unfortunately. But it is valid certificate.
I'm not really sure how to proceed with this. Maybe @frlan has some ideas regarding whether to continue using the cacert.org certificate or to look for alternatives.

And yes, the current Geany website is more or less broken when accessed  via SSL. In favor of this new website project, I personally do not want to fix this old site.

**Comment by genodeftest** [comment]
The original issue seems to be fixed. Thank you!

**Pull request closed without merging**
